# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a8abaa84e70d6046137fdefd63819b2ba9db6ce24eb212de2b7b653ef11675f8fd81e164e93b5ef7b08a33a439c901b90b4eccde4fe2ef5a8dc2164c4b0801d

test:
  secret_key_base: 3fd0b4afcd74533918b4b64c6bb737e32b79b9fe2751a92cbda945587459583eb68386457076a362325fb024395dec281c44ee780bf77ad2f16107f777ca1855

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
